CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stocks (
  id SERIAL PRIMARY KEY,
  symbol VARCHAR(50) NOT NULL UNIQUE,
  quantity INT NOT NULL,
  total_invested DECIMAL(10,2) NOT NULL,
  sector VARCHAR(100) NOT NULL,
  status VARCHAR(20) DEFAULT 'Neutral' CHECK (status IN ('Good', 'Bad', 'Neutral')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
